version: 2.1
jobs:
  build:
    docker:
      - image: <<parameters.docker_image>>
    parameters:
        tox_env:
            type: string
        docker_image:
            type: string
    steps:
      - checkout
      - run:
          name: Update system
          command: |
            sudo sed -i '/jessie-updates/d' /etc/apt/sources.list
            sudo sed -i '/jessie-backports/d' /etc/apt/sources.list
            sudo apt-get update
            sudo apt-get install -y libgtk3.0-cil-dev libasound2 libasound2 libdbus-glib-1-2 libdbus-1-3 libgtk2.0-0
      - run:
          name: Install firefox 38.0.5
          command: |
            FIREFOX_URL="https://sourceforge.net/projects/ubuntuzilla/files/mozilla/apt/pool/main/f/firefox-mozilla-build/firefox-mozilla-build_38.0.5-0ubuntu1_amd64.deb/download"
            sudo apt-get update
            curl --silent --show-error --location --fail --retry 3 --output /tmp/firefox.deb $FIREFOX_URL
            ls /tmp/
            sudo dpkg -i /tmp/firefox.deb
            rm -rf /tmp/firefox.deb
            firefox --version
            which firefox
      - run: 
          name: Sync submodules
          command: git submodule sync
      - run: 
          name: Update submodules
          command: git submodule update --init
      - run:
          name: Setup tox
          command: virtualenv venv && venv/bin/pip install tox
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/coverage/$CIRCLE_SHA1
            venv/bin/tox -e <<parameters.tox_env>>
            if [ -e .coverage.* ]; then
                cp .coverage.* /tmp/coverage/$CIRCLE_SHA1/.
            fi
      - persist_to_workspace:
          root: /tmp
          paths:
              - coverage

  coverage:
    docker:
      - image: <<parameters.docker_image>>
    parameters:
        docker_image:
            type: string
    steps:
      - checkout
      - run:
          name: Update system
          command: |
            # The jessie-updates and jessie-backports areas are now removed from the repositories. So
            # the lines corresponding to those areas have to be removed to fix the resulting errors.
            # This can be removed after upgrading to the image based on Debian Stretch.
            sudo sed -i '/jessie-updates/d' /etc/apt/sources.list
            sudo sed -i '/jessie-backports/d' /etc/apt/sources.list
            sudo apt-get update
            sudo pip install --upgrade pip
            sudo pip install --upgrade virtualenv
            virtualenv venv
            source venv/bin/activate
            pip install -r test_requirements.txt
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
              source venv/bin/activate
              coverage combine /tmp/workspace/coverage/$CIRCLE_SHA1/
              coverage report

  deploy:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "setup.py" }}
      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -U pip twine wheel
      - save_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          name: Verify commit is tagged and tag matches version
          command: |
            . venv/bin/activate
            python setup.py verify_tag
      - run:
          name: Initialize .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = opencraft" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Create packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: Upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

  deploy_python3:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "setup.py" }}
      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -U pip twine wheel
      - save_cache:
          key: dependencies-{{ checksum "circle.yml" }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          name: Verify commit is tagged and tag matches version
          command: |
            . venv/bin/activate
            python setup.py verify_tag
      - run:
          name: Initialize .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = opencraft" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Create packages
          command: |
            python setup.py bdist_wheel
      - run:
          name: Upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          name: py27-quality
          tox_env: py27-quality
          docker_image: circleci/python:2.7.14-browsers
          filters:
            tags:
              only: /.*/
      - build:
          name: py27-django111-unit
          tox_env: py27-django111-unit
          docker_image: circleci/python:2.7.14-browsers
          filters:
            tags:
              only: /.*/
      - build:
          name: py27-django111-integration
          tox_env: py27-django111-integration
          docker_image: circleci/python:2.7.14-browsers
          filters:
            tags:
              only: /.*/
      - coverage:
          name: py27-coverage
          docker_image: circleci/python:2.7.14
          filters:
            tags:
              only: /.*/
          requires:
              - py27-quality
              - py27-django111-unit
              - py27-django111-integration
      - deploy:
          name: py27-deploy
          requires:
            - py27-coverage
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

      - build:
          name: py35-quality
          tox_env: py35-quality
          docker_image: circleci/python:3.5-browsers
          filters:
            tags:
              only: /.*/
      - build:
          name: py35-django111-unit
          tox_env: py35-django111-unit
          docker_image: circleci/python:3.5-browsers
          filters:
            tags:
              only: /.*/
      - build:
          name: py35-django111-integration
          tox_env: py35-django111-integration
          docker_image: circleci/python:3.5-browsers
          filters:
            tags:
              only: /.*/
      - coverage:
          name: py35-coverage
          docker_image: circleci/python:3.5
          filters:
            tags:
              only: /.*/
          requires:
              - py35-quality
              - py35-django111-unit
              - py35-django111-integration
      - deploy_python3:
          name: py35-deploy
          requires:
            - py35-coverage
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
